---
# tasks file for first_role
- name: Add test.txt file
  file:
    path: /home/ec2-user/Ansible_Workbook/test.txt
    state: touch

- name: Add line in file
  lineinfile:
    path: /home/ec2-user/Ansible_Workbook/test.txt
    line: "{{ line }}"

- name: Add line2 in file
  lineinfile:
    path: /home/ec2-user/Ansible_Workbook/test.txt
    line: "{{ line2 }}"