---
# tasks file for second_role
- name: Add several users to a group 
  user:
    name: "{{ item }}"
    state: present # absent to remove
    groups: "wheel"
  loop:
    - testuser1
    - testuser2
    - testuser3
    - testuser4
    - testuser5